### PR TITLE
24 bring data.validator back on cran

### PR DESCRIPTION
**Pull request by scizmeli**
### Link to the issue
#24 

Before submitting a PR please answer:
* Was it necessary to update README? Is README updated? Yes
* Are unit tests added for new logic? No new logic.

### CODE REVIEW

**Review by przytu1 — CHANGES_REQUESTED** [review]
Hello @scizmeli 👋 Thank you for taking care of this issue. I have 2 remarks:

1. Could you please investigate and fix automatic checks on macOS-latest and ubuntu-18.04? We require all checks to pass before merging to master.

2. Could you explain why only version bump to 0.1.6, bumping Roxygen and adding you as contributor to DESCRIPTION fixes the problem? What was the exact reason that data.validator was taken down from CRAN?

**Comment by scizmeli** [comment]
Hi Pawel,

1. I am looking into why it is failing on Linux and Mac. I see the errors produced in the logs and trying to find out how to fix them. I never worked with Github actions before. Right now I am reading and getting used to the whole thing.
2. CRAN (https://cran.r-project.org/web/packages/data.validator/index.html) says  `Archived on 202111-02 as requires archived package 'shiny.semantic'.`. Since I know that you guys already brought shiny.semantic back online, I thought simply re-submitting data.validator will be enough. Am I missing something? As per the version number, I thought these simple cosmetic changes I did should only grant the smallest version number change possible, hence my choice of 0.1.5->0.1.6. Any other recommendations?

**Comment by scizmeli** [comment]
Hi Pawel, 

I solved the Github action problems 
- For MacOS R version had to be upgraded to 4.1.2. 
- For consistency I upgraded the R version in the two other platforms as well.
- For Linux, I also had to change the Linux system deps installation method which I imported from shiny.semantic.

Awaiting your feedback on my previous message on version numbering.

**Review by przytu1 — APPROVED** [review]
LGTM. Thank you Ahmet :100:

**Pull request merged**
